log:
  level: debug
  path: ./logs
  size: 10
  expire: 3
  limit: 15
  stdout: true
server:
  grpc:
    addr: 0.0.0.0:10115
    timeout: 15s
data:
  databases:
    - name: datahub
      dsn: yourUsername:yourPassword@tcp(mysql.mysql.svc.cluster.local:4000)/datahub?parseTime=True&loc=Local
  redis:
    master: "redis-master"
    password: "yourPassword"
    sentinelAddrs:
      - "sentinel0.redis.svc.cluster.local:5000"
      - "sentinel1.redis.svc.cluster.local:5000"
      - "sentinel2.redis.svc.cluster.local:5000"