log:
  level: debug
  path: ./logs
  size: 10
  expire: 3
  limit: 15
  stdout: true
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    - name: mysql
      source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    master: "aoni-master"
    password: "eptest$00"
    sentinelAddrs:
      - "aoni-redis:26379"
      - "aoni-redis:26479"
      - "aoni-redis:26579"
